SELECT statistic_dt AS "date",
source_system_nm AS "platform",
advertiser_nm AS "advertiser",
ad_environment_typ AS "ad_environment",
campaign_nm AS "campaign",
ad_group_nm AS "ad_group",
creative_nm AS "ad",
creative_typ AS "ad_type",
ad_format_txt AS "ad_dimensions",
tracking_tag_1_nm AS "kpi_1_name",
tracking_tag_2_nm AS "kpi_2_name",
tracking_tag_3_nm AS "kpi_3_name",
tracking_tag_4_nm AS "kpi_4_name",
tracking_tag_5_nm AS "kpi_5_name",
purchase_order_num AS "order_id",
SUM(bids_cnt) AS "bids",
SUM(impressions_cnt) AS "impressions",
SUM(clicks_cnt) AS "clicks",
SUM(advertiser_cost_usd_amt) AS "media_cost",
SUM(player_complete_quarter_cnt) AS "video_played_to_25%",
SUM(player_complete_half_cnt) AS "video_played_to_50%",
SUM(player_complete_three_quarter_cnt) AS "video_played_to_75%",
SUM(player_close_cnt) AS "video_player_closes",
SUM(player_collapse_cnt) AS "video_player_collapses",
SUM(player_completed_views_cnt) AS "video_played_to_100%",
SUM(player_errors_cnt) AS "video_player_errors",
SUM(player_full_screen_cnt) AS "video_player_full_screen",
SUM(player_invitation_accept_cnt) AS "video_player_invitation_accepts",
SUM(player_mute_cnt) AS "video_player_mutes",
SUM(player_pause_cnt) AS "video_player_pauses",
SUM(player_resume_cnt) AS "video_player_resumes",
SUM(player_rewind_cnt) AS "video_player_rewinds",
SUM(player_skip_cnt) AS "video_player_skips",
SUM(player_starts_cnt) AS "video_player_starts",
SUM(player_unmute_cnt) AS "video_player_unmutes",
SUM(player_views_cnt) AS "video_views",
SUM(player_expansion_cnt) AS "video_player_expansions",
SUM(sampled_tracked_impressions_cnt) AS "tracked_impressions",
SUM(sampled_viewed_impressions_cnt) AS "viewed_impressions",
SUM(c01_click_conversion_cnt) AS "kpi_1_click_conversions",
SUM(c01_click_conversion_revenue_amt) AS "kpi_1_click_conversion_revenue",
SUM(c01_view_through_conversion_cnt) AS "kpi_1_view_through_conversions",
SUM(c01_view_through_conversion_revenue_amt) AS "kpi_1_view_through_conversion_revenue",
SUM(c01_total_click_and_view_conversions_cnt) AS "kpi_1_total_conversions",
SUM(c02_click_conversion_cnt) AS "kpi_2_click_conversions",
SUM(c02_click_conversion_revenue_amt) AS "kpi_2_click_conversion_revenue",
SUM(c02_view_through_conversion_cnt) AS "kpi_2_view_through_conversions",
SUM(c02_view_through_conversion_revenue_amt) AS "kpi_2_view_through_conversion_revenue",
SUM(c02_total_click_and_view_conversions_cnt) AS "kpi_2_total_conversions",
SUM(c03_click_conversion_cnt) AS "kpi_3_click_conversions",
SUM(c03_click_conversion_revenue_amt) AS "kpi_3_click_conversion_revenue",
SUM(c03_view_through_conversion_cnt) AS "kpi_3_view_through_conversions",
SUM(c03_view_through_conversion_revenue_amt) AS "kpi_3_view_through_conversion_revenue",
SUM(c03_total_click_and_view_conversions_cnt) AS "kpi_3_total_conversions",
SUM(c04_click_conversion_cnt) AS "kpi_4_click_conversions",
SUM(c04_click_conversion_revenue_amt) AS "kpi_4_click_conversion_revenue",
SUM(c04_view_through_conversion_cnt) AS "kpi_4_view_through_conversions",
SUM(c04_view_through_conversion_revenue_amt) AS "kpi_4_view_through_conversion_revenue",
SUM(c04_total_click_and_view_conversions_cnt) AS "kpi_4_total_conversions",
SUM(c05_click_conversion_cnt) AS "kpi_5_click_conversions",
SUM(c05_click_conversion_revenue_amt) AS "kpi_5_click_conversion_revenue",
SUM(c05_view_through_conversion_cnt) AS "kpi_5_view_through_conversions",
SUM(c05_view_through_conversion_revenue_amt) AS "kpi_5_view_through_conversion_revenue",
SUM(c05_total_click_and_view_conversions_cnt) AS "kpi_5_total_conversions"
FROM
vw_ttd_performance 
WHERE
advertiser_id = 'uqzz9qe'
GROUP BY
statistic_dt,
source_system_nm, 
advertiser_nm,
ad_environment_typ, 
campaign_nm,
ad_group_nm,
creative_nm,
creative_typ, 
ad_format_txt,
tracking_tag_1_nm, 
tracking_tag_2_nm,
tracking_tag_3_nm,
tracking_tag_4_nm,
tracking_tag_5_nm,
purchase_order_num
ORDER BY statistic_dt;






